import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isRasterFile } from './lib/privacy.mjs';

const skillRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const forbiddenDirectories = new Set(['preview', 'release', 'dist', 'node_modules']);
const ignoredDirectories = new Set(['.git']);
const errors = [];
const files = [];
const stack = [skillRoot];

while (stack.length) {
  const current = stack.pop();
  for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
    const full = path.join(current, entry.name);
    const relative = path.relative(skillRoot, full);
    if (entry.isDirectory()) {
      if (ignoredDirectories.has(entry.name)) continue;
      if (forbiddenDirectories.has(entry.name)) errors.push(`Generated/runtime directory must not be published inside the Skill: ${relative}`);
      else stack.push(full);
      continue;
    }
    if (!entry.isFile()) continue;
    files.push(relative);
    if (isRasterFile(full)) errors.push(`Raster image must be generated by the current user, not bundled in the Skill: ${relative}`);
    if (path.extname(entry.name).toLowerCase() === '.svg' && /data:image\//i.test(fs.readFileSync(full, 'utf8'))) {
      errors.push(`SVG must not embed raster image data: ${relative}`);
    }
    if (fs.statSync(full).size > 1024 * 1024) errors.push(`Unexpected file larger than 1 MiB: ${relative}`);
  }
}

if (!files.includes(path.join('assets', 'electron-template', 'src', 'assets', 'sprites', 'placeholder.svg'))) {
  errors.push('The generic SVG placeholder is missing from the Electron template.');
}

if (errors.length) {
  console.error(errors.map((error) => `- ${error}`).join('\n'));
  process.exit(1);
}

console.log(`Release privacy audit passed: ${files.length} files, no bundled raster/person assets.`);
