import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isRasterFile, sensitivePathMatches } from './lib/privacy.mjs';

const args = process.argv.slice(2);
const rootIndex = args.indexOf('--root');
const defaultSkillRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const skillRoot = rootIndex >= 0 ? path.resolve(args[rootIndex + 1] || '') : defaultSkillRoot;
const forbiddenDirectories = new Set(['preview', 'release', 'dist', 'node_modules']);
const ignoredDirectories = new Set(['.git']);
const piiTextExtensions = new Set(['.json', '.md', '.yaml', '.yml', '.txt', '.log']);
const reservedEmailDomains = new Set(['example.com', 'example.net', 'example.org', 'example.test']);
const errors = [];
const files = [];
const stack = [skillRoot];

if (rootIndex >= 0 && !args[rootIndex + 1]) {
  console.error('- --root requires a directory.');
  process.exit(1);
}

function piiIssues(text) {
  const issues = [];
  const emails = text.match(/[A-Z0-9._%+-]+@([A-Z0-9.-]+\.[A-Z]{2,})/gi) || [];
  if (emails.some((email) => !reservedEmailDomains.has(email.split('@').at(-1).toLowerCase()))) {
    issues.push('email address');
  }
  if (/(?:姓名|真实姓名|联系人姓名|full\s+name|legal\s+name|contact\s+name)\s*[:：]\s*(?!<|\[|\{|example\b|test\b|placeholder\b|your\b)\S+/im.test(text)) {
    issues.push('personal name');
  }
  if (/(?:微信号?|wechat(?:\s+id)?|qq号?|账号|account(?:\s+(?:id|name))?|用户名|username)\s*[:：]\s*(?!<|\[|\{|example\b|test\b|placeholder\b|your\b|person-\d+\b)\S+/im.test(text)) {
    issues.push('account identifier');
  }
  if (sensitivePathMatches(text).length) issues.push('private path');
  return issues;
}

while (stack.length) {
  const current = stack.pop();
  for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
    const full = path.join(current, entry.name);
    const relative = path.relative(skillRoot, full);
    if (entry.isDirectory()) {
      if (ignoredDirectories.has(entry.name)) continue;
      if (forbiddenDirectories.has(entry.name)) errors.push(`Generated/runtime directory must not be published inside the Skill: ${relative}`);
      else stack.push(full);
      continue;
    }
    if (!entry.isFile()) continue;
    files.push(relative);
    if (isRasterFile(full)) errors.push(`Raster image must be generated by the current user, not bundled in the Skill: ${relative}`);
    if (path.extname(entry.name).toLowerCase() === '.svg' && /data:image\//i.test(fs.readFileSync(full, 'utf8'))) {
      errors.push(`SVG must not embed raster image data: ${relative}`);
    }
    if (fs.statSync(full).size > 1024 * 1024) errors.push(`Unexpected file larger than 1 MiB: ${relative}`);
    if (piiTextExtensions.has(path.extname(entry.name).toLowerCase())) {
      for (const issue of piiIssues(fs.readFileSync(full, 'utf8'))) {
        errors.push(`Text ${issue} must not be published in the Skill: ${relative}`);
      }
    }
  }
}

if (!files.includes(path.join('assets', 'electron-template', 'src', 'assets', 'sprites', 'placeholder.svg'))) {
  errors.push('The generic SVG placeholder is missing from the Electron template.');
}

if (errors.length) {
  console.error(errors.map((error) => `- ${error}`).join('\n'));
  process.exit(1);
}

console.log(`Release privacy audit passed: ${files.length} files, no bundled raster/person assets.`);
